---
name: "Surf embedded browser"
version: "0.0.2"
slug: embdbrowser
description: "Surf embedded browser"
url: https://github.com/Aledan862/addon-embedded-browser/tree/main/embedded_browser
arch:
  - amd64
  - armhf
  - aarch64
  - armv7
  - i386
apparmor: false
host_network: false
stage: experimental
init: false
hassio_api: true
privileged:
  - NET_ADMIN
udev: false
usb: false
startup: services
ingress: true
ingress_entry: ingress.html
kernel_modules: false
image: "bigmoby/{arch}-addon-embedded-browser"
